let arr = ['qwe', undefined, NaN, false, 145, 78, 'okten', true, -564, 'boolean'];
console.log(arr[0]);
console.log(arr[9]);
console.log(arr[1]);
console.log(arr[8]);
console.log(arr[2]);
console.log(arr[7]);
console.log(arr[3]);
console.log(arr[6]);
console.log(arr[4]);
console.log(arr[5]);